name: Build, Test and Push a
on:
  release:
    types: [published]
  push:
    branches:
    - '**'
    tags:
    - v*
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: echo start
      run: |
        echo "build-and-test executing"

  build-and-push:
    needs: build-and-test
    if: github.event_name == 'push' || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: |
        echo "${{ github.ref }}"
        echo "build-and-push executing"
  
