name: Build, Test and Push a
on:
  push:
    paths:
      - 'a/**'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: echo start
      run: |
        echo "build-and-test a executing"

  build-and-push-a:
    needs: build-and-test
    if: github.event_name == 'push' # not pull request
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: |
        echo "build-and-push a executing"
  
